#!/usr/bin/env node
// tests/smoke.mjs — the whole test suite for the docs site.
//
// WHY THIS FILE IS THE ENTIRE SUITE
//   The docs repository has no runtime: it is Markdown plus a build. The only
//   thing that can break is the build, and the build is the gate
//   (`bin/prime` = `npm ci && npm run build && npm test`). So this test's job
//   is to assert that a build actually produced a site, and specifically the
//   pages the navigation in astro.config.mjs promises. A green `npm run build`
//   with an empty dist/ would otherwise pass silently.
//
// WHAT IT ASSERTS (and what it deliberately does not)
//   - dist/index.html exists, is non-empty, and is an HTML document.
//   - Every page linked from the sidebar has a source file AND reached dist/.
//     Starlight does fail the build on a dangling sidebar slug, so this is
//     deliberately redundant with the build: it names the broken slug in one
//     line, and it still catches a page that built but was never emitted.
//   - The reverse: every page in src/content/docs/ is reachable from the
//     sidebar. A page on disk and absent from the nav is a page nobody reads,
//     and nothing else in the pipeline notices.
//   - No built page contains an empty <svg>, which is what an icon name
//     Starlight does not know renders to.
//   - No HTML snapshot, no assertion on prose. A snapshot is a test that fails
//     on every copy edit and gets deleted within a week, which is worse than
//     no test. Content correctness is the author's job, checked in review.
//
// SIDEBAR DERIVATION — why this file parses astro.config.mjs instead of
// hardcoding the page list
//   A hardcoded list is a second source of truth that drifts: add a sidebar
//   entry, forget this file, and the test quietly stops checking the new page.
//   So the expected routes are read from the config, the one place a page is
//   actually promised. Every `slug:` there must resolve to a file under
//   src/content/docs/ AND to HTML in dist/.
//
//   The config is read as text rather than imported, on purpose. Importing it
//   would need the Starlight integration resolvable and would execute the
//   integration; reading it keeps `npm test` runnable on its own.
import { strict as assert } from 'node:assert';
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { test } from 'node:test';

const root = resolve(import.meta.dirname, '..');
const dist = join(root, 'dist');
const docs = join(root, 'src', 'content', 'docs');
const configFile = join(root, 'astro.config.mjs');

/**
 * Strip comments and string literals out of a JS source file, so a `slug:`
 * inside a comment cannot become a test assertion. Line comments and block
 * comments only — the config has no regex literals or template strings whose
 * contents matter here.
 */
function stripComments(source) {
  return source.replace(/\/\*[\s\S]*?\*\//g, '').replace(/(^|[^:])\/\/.*$/gm, '$1');
}

/** Every `slug: '…'` in the sidebar, plus the literals of any `{ link: '/' }`. */
function sidebarSlugs() {
  const source = stripComments(readFileSync(configFile, 'utf8'));
  const slugs = [...source.matchAll(/slug:\s*'([^']+)'/g)].map((m) => m[1]);
  const links = [...source.matchAll(/\blink:\s*'([^']*)'/g)].map((m) => m[1]);
  return { slugs, links };
}

/**
 * Every directory the sidebar autogenerates from.
 *
 * A directory entry covers its pages implicitly, so the reverse-coverage test
 * below has to read it — otherwise every service page looks unreachable and
 * the assertion is unsatisfiable rather than true.
 */
function autogeneratedDirectories() {
  const source = stripComments(readFileSync(configFile, 'utf8'));
  return [...source.matchAll(/autogenerate:\s*\{\s*directory:\s*'([^']+)'/g)].map((m) => m[1]);
}

/** Every content page on disk, as canonical URL paths, excluding the home page. */
function contentPages() {
  const pages = [];
  const walk = (dir, prefix = '') => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const rel = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        walk(join(dir, entry.name), rel);
      } else if (/\.mdx?$/.test(entry.name)) {
        const stem = rel.replace(/\.mdx?$/, '');
        // Starlight's docsLoader drops a trailing `/index`, so
        // `runbooks/index.md` and `runbooks.md` are the same slug. The home
        // page (`index.mdx`) slugifies to the empty string, which is `/`.
        pages.push(canonicalPath(stem.replace(/\/index$/, '').replace(/^index$/, '')));
      }
    }
  };
  walk(docs);
  return pages.sort();
}

/** One leading slash, no trailing slash, `/` for the empty path. */
function canonicalPath(p) {
  const trimmed = p.replace(/^\/+/, '').replace(/\/+$/, '');
  return trimmed === '' ? '/' : `/${trimmed}`;
}

/**
 * The content file a Starlight slug maps to. Starlight's docsLoader sluggifies
 * the filename and drops the extension, so `services/identity.md` serves
 * `/services/identity/`. Directories get an `index` file.
 */
function sourceFileFor(slug) {
  const base = slug.replace(/^\/+|\/+$/g, '');
  const asFile = base ? join(docs, `${base}.md`) : join(docs, 'index.mdx');
  const asDir = join(docs, base, 'index.md');
  return existsSync(asFile)
    ? asFile
    : existsSync(join(docs, `${base}.mdx`))
      ? join(docs, `${base}.mdx`)
      : asDir;
}

/** The built HTML path for a URL path, matching Astro's default `directory` format. */
function htmlFor(urlPath) {
  const clean = urlPath.replace(/^\/+/, '').replace(/\/+$/, '');
  return clean === '' ? 'index.html' : `${clean}/index.html`;
}

test('dist/index.html exists, is non-empty, and is HTML', () => {
  const index = join(dist, 'index.html');
  assert.ok(
    existsSync(index),
    `dist/index.html missing — run \`npm run build\` before \`npm test\` (looked in ${dist})`,
  );
  assert.ok(statSync(index).size > 0, 'dist/index.html is empty');
  assert.match(readFileSync(index, 'utf8'), /<html/i, 'dist/index.html is not an HTML document');
});

test('every sidebar slug has a page in src/content/docs/', () => {
  const { slugs } = sidebarSlugs();
  assert.ok(slugs.length > 0, 'no sidebar slugs found — did astro.config.mjs change shape?');

  const missing = slugs
    .map((slug) => [slug, sourceFileFor(slug)])
    .filter(([, file]) => !existsSync(file))
    .map(([slug, file]) => `${slug} (looked for ${file})`);

  assert.deepEqual(missing, [], `sidebar slugs with no content file: ${missing.join('; ')}`);
});

test('every sidebar slug is in dist/ after a build', () => {
  const { slugs, links } = sidebarSlugs();
  const routes = [
    ...slugs.map((slug) => `/${slug}/`),
    // `link:` entries are absolute URLs or site-relative paths; an external
    // URL is not our page to build.
    ...links.filter((href) => href.startsWith('/')).map((href) => href),
  ];

  const missing = routes
    .map((route) => [route, htmlFor(route)])
    .filter(([, html]) => !existsSync(join(dist, html)))
    .map(([route, html]) => `${route} -> ${html}`);

  assert.deepEqual(
    missing,
    [],
    `sidebar routes missing from dist/: ${missing.join(', ')} — run \`npm run build\` first`,
  );
});

test('the services directory is not empty', () => {
  const services = join(docs, 'services');
  assert.ok(existsSync(services), 'src/content/docs/services/ is missing');
  const pages = readdirSync(services).filter((f) => /\.mdx?$/.test(f));
  assert.ok(pages.length > 0, 'no service pages found in src/content/docs/services/');
});

test('every internal link in the built site resolves', () => {
  // AGENTS.md names a broken link as one of the two ways this repository breaks
  // quietly: nothing validates an href, Starlight does not rewrite or check
  // them, and a page can point at a slug that was renamed two commits ago and
  // still build green. That is a 404 a reader finds, not a red build a reviewer
  // sees.
  const pages = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.html')) pages.push(full);
    }
  };
  walk(dist);
  assert.ok(pages.length > 0, `no HTML under ${dist} — run \`npm run build\` first`);

  // Scanned over dist/ rather than over the Markdown, because that is what a
  // reader's browser resolves and it also catches links Starlight's components
  // emit rather than ones an author typed.
  const source = pages.map((page) => readFileSync(page, 'utf8')).join('\n');

  // Asset references are not links. `<link rel="icon">` and friends point at a
  // file the browser fetches on its own; nothing in the navigation depends on
  // them resolving, and treating them as links conflates two failures.
  //
  // One is nevertheless outstanding and this assertion says so out loud rather
  // than absorbing it: Starlight's favicon schema is
  // `z.string().default('/favicon.svg')` with no way to omit it, and this
  // repository has no brand asset to put there. Inventing a mark is a brand
  // decision this repository has explicitly not made (see the `logo:` note in
  // astro.config.mjs), so the 404 stands, recorded, until that decision is.
  //
  // The exception is asserted to be EXACTLY this list rather than filtered by a
  // pattern, so a second asset 404 fails the suite instead of joining a growing
  // allowlist nobody reads.
  const knownMissingAssets = ['/favicon.svg'];
  const assetRefs = [
    ...source.matchAll(/<link\b[^>]*rel="[^"]*\bicon\b[^"]*"[^>]*>/g),
  ]
    .map((tag) => tag[0].match(/href="([^"]+)"/)?.[1])
    .filter((href) => href?.startsWith('/'));

  assert.deepEqual(
    [...new Set(assetRefs)].sort(),
    knownMissingAssets,
    'the set of referenced static assets changed. If the favicon now exists, ' +
      'delete it from knownMissingAssets in this file and from public/. If a new ' +
      'asset was added and is missing from dist/, ship it or remove the reference.',
  );

  const hrefs = [...source.matchAll(/href="([^"]+)"/g)].map((m) => m[1]);
  const internal = [
    ...new Set(
      hrefs
        .filter((h) => h.startsWith('/') && !h.startsWith('//'))
        .map((h) => h.split('#')[0]),
    ),
  ].filter((h) => h !== '' && !knownMissingAssets.includes(h));

  // `trailingSlash: 'ignore'` means either spelling may be served, so accept
  // either — but not neither. A host that serves /x/ and not /x is its own
  // decision; a site that ships neither is broken.
  const resolves = (urlPath) => {
    const clean = urlPath.replace(/^\/+/, '').replace(/\/+$/, '');
    if (clean === '') return existsSync(join(dist, 'index.html'));
    return (
      existsSync(join(dist, clean, 'index.html')) ||
      existsSync(join(dist, `${clean}.html`)) ||
      existsSync(join(dist, clean))
    );
  };

  const broken = internal.filter((href) => !resolves(href)).sort();

  assert.deepEqual(
    broken,
    [],
    `internal links with nothing in dist/ behind them: ${broken.join(', ')} — a ` +
      'renamed or deleted page whose inbound links were not updated',
  );
});

test('no built page contains an empty <svg>', () => {
  // An icon name Starlight does not know renders as an empty <svg> — no
  // warning, no build failure, and a card that looks slightly wrong rather than
  // broken. That is worse than a red build, because nothing reports it.
  //
  // Found by writing one: `icon="seti:changelog"` is a valid *Seti UI* name and
  // Starlight 0.42 has no `seti:` prefix support at all, so the card shipped an
  // empty element for a whole release cycle. It is asserted here because the
  // only way to know an icon resolved is to look at the built output, and
  // nothing else in the pipeline looks.
  //
  // The scan is over the rendered pages rather than the Markdown, so it catches
  // an empty icon anywhere — a Card, an Aside, a component prop — rather than
  // only the two or three places an icon is written today.
  const pages = [];
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) walk(full);
      else if (entry.name.endsWith('.html')) pages.push(full);
    }
  };
  walk(dist);
  assert.ok(pages.length > 0, `no HTML under ${dist} — run \`npm run build\` first`);

  // `<svg …/>` or `<svg …></svg>` with nothing between the tags. Attribute
  // values are matched loosely because the class hashes change per build.
  const empty = /<svg\b[^>]*\/>|<svg\b[^>]*>\s*<\/svg>/g;
  const offenders = pages
    .filter((page) => empty.test(readFileSync(page, 'utf8')))
    .map((page) => page.slice(dist.length + 1));
  assert.deepEqual(
    offenders,
    [],
    `pages containing an empty <svg> (an icon name Starlight does not know, most ` +
      `likely — check the name against the list in ` +
      '`node_modules/@astrojs/starlight/dist/components-internals/Icons.js`): ' +
      offenders.join(', '),
  );
});

test('every content page is reachable from the sidebar', () => {
  // The other direction, and the one that was missing.
  //
  // The three assertions above are sidebar -> disk. A page that is on disk and
  // absent from the navigation passes all of them: it builds, it lands in
  // dist/, and nothing looks broken. That is the quiet failure this repository
  // has the least defence against — a reader who cannot find the migration note
  // or the gates page concludes it does not exist, and the page that was
  // written carefully to correct a wrong claim is the one nobody reads.
  //
  // Starlight's own behaviour is why: the docs collection picks up every file
  // under `src/content/docs/` whether or not the sidebar mentions it, so the
  // build is silent about a page that is only reachable by typing its URL.
  const { slugs, links } = sidebarSlugs();
  const directories = autogeneratedDirectories();
  const covered = new Set([...slugs.map(canonicalPath), ...links.map(canonicalPath)]);

  const orphans = contentPages().filter((page) => {
    if (covered.has(page)) return false;
    // An autogenerated group covers its own index page and everything beneath it.
    return !directories.some((dir) => {
      const base = canonicalPath(dir);
      return page === base || page.startsWith(`${base}/`);
    });
  });

  assert.deepEqual(
    orphans,
    [],
    `content pages with no sidebar entry: ${orphans.join(', ')} — add the page and ` +
      'the sidebar entry in the same commit (astro.config.mjs)',
  );
});